package md.thomas.openoura.store

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import java.security.MessageDigest
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES/GCM sealing against a non-exportable Android Keystore key. Used for the ring auth
 * key, whose iOS counterpart is a Keychain generic-password item.
 *
 * The IV is generated by the provider and prefixed to the ciphertext, so callers hold a
 * single opaque string. Deliberately NOT `setUserAuthenticationRequired`: the app syncs
 * opportunistically in the background, where no unlock prompt can be shown.
 */
internal object Crypto {
    private const val KEYSTORE = "AndroidKeyStore"
    private const val ALIAS = "openoura.ring-key"
    private const val TRANSFORM = "AES/GCM/NoPadding"
    private const val TAG_BITS = 128
    private const val IV_BYTES = 12

    fun encrypt(plain: ByteArray): String {
        val cipher = Cipher.getInstance(TRANSFORM)
        cipher.init(Cipher.ENCRYPT_MODE, key())
        val iv = cipher.iv
        val body = cipher.doFinal(plain)
        return Base64.encodeToString(iv + body, Base64.NO_WRAP)
    }

    fun decrypt(sealed: String): ByteArray {
        val raw = Base64.decode(sealed, Base64.NO_WRAP)
        require(raw.size > IV_BYTES) { "sealed value too short" }
        val cipher = Cipher.getInstance(TRANSFORM)
        cipher.init(
            Cipher.DECRYPT_MODE,
            key(),
            GCMParameterSpec(TAG_BITS, raw, 0, IV_BYTES),
        )
        return cipher.doFinal(raw, IV_BYTES, raw.size - IV_BYTES)
    }

    private fun key(): SecretKey {
        val ks = KeyStore.getInstance(KEYSTORE).apply { load(null) }
        (ks.getEntry(ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }
        val gen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE)
        gen.init(
            KeyGenParameterSpec.Builder(
                ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .build()
        )
        return gen.generateKey()
    }
}

/**
 * Short, non-reversible identifier for a secret, so diagnostics can say *which* key was
 * used without ever printing it. Matches the iOS 4-byte SHA-256 prefix.
 */
fun secretFingerprint(value: String): String =
    MessageDigest.getInstance("SHA-256")
        .digest(value.trim().toByteArray(Charsets.UTF_8))
        .take(4)
        .joinToString("") { "%02x".format(it) }
